MIGI-32: Add reusable workflows doc
zupit-it/pipeline-templates pull request #1
Opened 2022-11-17 13:39 UTC by ivan-morandi-zupit

2022-11-17 13:40 UTC, ivan-morandi-zupit commented on .github/workflows/django-step-lint-check.yml
> -      PYTHON_VERSION:
non veniva utilizzato (probabilmente mi era rimasto indietro), quindi visto che siamo in tempo ho fatto pulizia

2022-11-17 13:41 UTC, ivan-morandi-zupit commented
se vuoi una preview della doc:
https://github.com/zupit-it/pipeline-templates/tree/MIGI-32/add-docs

2022-11-21 09:05 UTC, alessandro-mariotti-zupit requested changes

2022-11-22 10:44 UTC, alessandro-mariotti-zupit approved these changes

2022-11-22 11:15 UTC, ivan-morandi-zupit commented on README.md
> +#### NodeJS Common
l'idea è che vada bene per tutti i progetti NodeJS, alla fine noi chiamiamo solo dei comandi. L'unica cosa da modificare sarebbero i test cypress, ma per il resto mi sembra abbastanza modulabile.

2022-11-22 12:08 UTC, merged