MIGI-49: Add option to skip workflows to check code
zupit-it/pipeline-templates pull request #13
Opened 2022-12-14 12:32 UTC by ivan-morandi-zupit

2022-12-14 13:18 UTC, alessandro-mariotti-zupit reviewed
Aggiungerei docs/esempi su come si usa

2022-12-14 13:18 UTC, alessandro-mariotti-zupit requested changes
Aggiungerei docs /esempi su come si usa

2022-12-15 10:56 UTC, alessandro-mariotti-zupit approved these changes

2022-12-16 06:28 UTC, omar-muscatello-zupit approved these changes

2023-02-06 09:34 UTC, merged