MIGI-40: .NET pipeline
zupit-it/pipeline-templates pull request #16
Opened 2023-01-31 10:24 UTC by omar-muscatello-zupit

2023-02-06 09:35 UTC, alessandro-mariotti-zupit approved these changes

2023-02-06 10:27 UTC, ivan-morandi-zupit requested changes

2023-02-06 10:27 UTC, ivan-morandi-zupit commented on .github/workflows/sonar-step-analyze.yml
> +      CONTAINER_CI_LABELS:
ho memoria che ne avevamo parlato di questo giusto? mi ricordo un qualcosa per essere più leggibile, giusto?
va un attimo considerato il problema di questa modifica, ovvero che va a rompere tutte le pipeline esistenti :/
teniamo LABELS o aggiorniamo anche le altre pipe?

2023-02-20 08:10 UTC, omar-muscatello-zupit commented on .github/workflows/sonar-step-analyze.yml
> +      CONTAINER_CI_LABELS:
Quella modifica veniva dal fatto che quello step deve essere eseguito su container. Quindi il parametro `CONTAINER_CI_LABELS` conteneva implicitamente questa informazione, guidando l'utente nel non passare `native` come valore.

Però hai ragione, questo romperebbe le pipeline esistenti. Ho rimosso le modifiche, magari le facciamo quando siamo pronti.

2023-02-20 09:06 UTC, ivan-morandi-zupit approved these changes

2023-02-20 09:06 UTC, merged