TDSISD-43: Add SpringBoot and Jira documentation
zupit-it/pipeline-templates pull request #6
Opened 2022-11-24 09:41 UTC by ivan-morandi-zupit

2022-11-24 10:09 UTC, ivan-morandi-zupit commented
Per vedere il readme in maniera carina:
https://github.com/zupit-it/pipeline-templates/tree/MIGI-43/add-springboot-and-jira-doc

2022-11-24 10:22 UTC, davide-bontempelli-zupit requested changes

2022-11-24 10:22 UTC, davide-bontempelli-zupit commented on README.md
> +      2. [Build DOcker Image and Push to Registry](#springboot-build-docker-image-and-push-to-registry)
DOcker -> Docker

2022-11-24 10:22 UTC, davide-bontempelli-zupit commented on README.md
> +#### Jira Create TODO Issue
Specifica cosa succede se viene modificato o eliminato il todo

2022-11-24 14:26 UTC, alessandro-mariotti-zupit approved these changes

2022-11-25 08:30 UTC, davide-bontempelli-zupit approved these changes

2022-11-25 08:38 UTC, merged